# Generated by Django 3.1.7 on 2021-04-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210407_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Must Buy ', 'Must Buy '), ('Optional', 'Optional')], max_length=200, null=True),
        ),
    ]
